### ISSUE TITLE
Add gitter badge to readme (first-timers-only)

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/organization-contributors#5]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=org%3ADAVFoundation+is%3Aissue+is%3Aopen+label%3Afirst-timers-only).

Thank you for your help :heart:

## What is this project?

DAV (Decentralized Autonomous Vehicles) is a non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### organization-contributors

The project you are looking at is organization contributors. It is a command line tool for extracting the list of contributors across an entire Organization.

## How you can help

Your task for this issue is... In the [README.md](https://github.com/DAVFoundation/n3m0/blob/master/README.md) file add the following line of code 

````markdown
[![Gitter](https://img.shields.io/gitter/room/DAVFoundation/DAV-Contributors.svg?style=flat-square)](https://gitter.im/DAVFoundation/DAV-Contributors)
````

This will display a badge like this [![Gitter](https://img.shields.io/gitter/room/DAVFoundation/DAV-Contributors.svg?style=flat-square)](https://gitter.im/DAVFoundation/DAV-Contributors)

Have a look at the readme.md pages of other DAV projects for location of the badge.

### Contributing to organization-contributors

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [organization-contributors GitHub page](https://github.com/DAVFoundation/organization-contributors) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/organization-contributors.git`
- [ ] **Make changes in the Readme.md file**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/organization-contributors](https://github.com/YOUR-USER-NAME/organization-contributors)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#5`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by erickpazzim** [comment]
i would like to do this!

**Comment by cg-cnu** [comment]
Congratulations @erickpazzim on your first contribution to opensource 👏 Hope you had fun and learned few things. Feel free to join our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors/) to find out more opportunities to contribute. 😄
